### ISSUE TITLE
[TRG 5.02] Apache-2.0 License file missing in Chart

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/digital-product-pass#110]
The Apache License file has to be included in the Charts directory, so it is included in the released archive. See https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02/

blocks #108

**Comment by matbmoser** [comment]
Valid point 👍🏻 I will add it

**Comment by matbmoser** [comment]
@SebastianBezold  I created a PR waiting for your approval https://github.com/eclipse-tractusx/digital-product-pass/pull/117

**Comment by matbmoser** [comment]
PR merged this issue is ready to be closed :)
