### ISSUE TITLE
[TRG 5.01] Released Chart does contain environment specific values

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/digital-product-pass#111]
The released Chart archive does contain all of the environment specific yaml files.
This can be fixed by adding specific patterns to the `.helmignore` like described [here](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02#helmignore)

blocks #108

**Comment by matbmoser** [comment]
Included in v1.0.0-rc1 as commented before:
https://github.com/eclipse-tractusx/digital-product-pass/blob/main/charts/digital-product-pass/.helmignore
