### ISSUE TITLE
Check third party library license compliance

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/digital-product-pass#15]
In #14, dependency versions are updated. The following IP issues are created for unknown license compliance:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7858
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7859
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7860
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7861
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/7862

Please keep track of the issues. If all are solved, without any rejected libraries, #14 can be merged

FYI @matbmoser

**Comment by matbmoser** [comment]
@SebastianBezold all the issues are approved! We are ready to merge
