### ISSUE TITLE
TRG 1.04 diagrams as code / editable static files

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#182]
All diagram files must be either using code to generate diagrams, or stored as .svg file within our repositories. After a committers [decision](https://github.com/eclipse-tractusx/sig-infra/discussions/19) there are 2 languages accepted, either [PUML](https://plantuml.com/en/) or [Mermaid](https://mermaid.js.org/). If you're using a specific tool like Draw.io, describe how you created it and document the creation or modification process in your documentation files.

The diagram code files (.puml,.mmd,.mermaid) and / or static diagram .svg files must be stored within the docs/ folder as

For further details, visit this link: https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4

**Comment by matbmoser** [comment]
Me and @dsrparracho we updated all the diagrams from the docs folder to drawio svgs in this PR: #204 

I also updated before from the bussiness context to svgs in this PR: #198
