### ISSUE TITLE
updated copyright headers required

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/digital-product-pass#231]
Unfortunately all(?) of your copyright headers have to be updated.
The current ones are still stating
```# Catena-X - Digital Product Passport Application

Since you have moved to Tractus-X project this is no longer valid. Please replace it by "Tractus-X" or remove the whole line.

**Comment by matbmoser** [comment]
Solved in the release https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.1.3

**Comment by matbmoser** [comment]
Was also good we found some un updated license header years in the notices for documentation :)
