### ISSUE TITLE
configuration option missing in values file

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/digital-product-pass#234]
Hey,

as states in our [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) some additional values should be configurable in the values.yaml. I did not check all, but at least these two are missing:
- ingress class 
- Persistent storage configuration

Additionally TRG [5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) demands that all variables are present, got default values and got comments what they are doing

**Comment by matbmoser** [comment]
@hzierer is it enough that we update that in the main branch?

**Comment by hzierer** [comment]
sure, as long as you add it to future development branches too
