### ISSUE TITLE
Do we need to remove Catena-X Logos from Documentation?

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#236]
## Introduction

In the review for TRGs #180 we found out that there was a remark for documentation.

We need to clarify that. It does not blocks the QG but needs to be checked for future releases.

## Question: 

- **Is it necessary that we need to remove the logos from Catena-X?**
     - Example: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/catena-x-logo.svg

**Comment by AngelikaWittek** [comment]
Hi Mathias,
thanks for the question, we will provide guidelines how to use the logo for 24.05. This has be be coordinated with Catena-X.
Until then no action is required.
@SebastianBezold

**Comment by matbmoser** [comment]
Thank you @AngelikaWittek 👍🏻 

Let see what comes with the clarification.

**Comment by matbmoser** [comment]
I will close this ticket since there will be a guideline coordinated with Catena-X for the next release 24.05.

**Comment by matbmoser** [comment]
@AngelikaWittek I am confused. I was here thinking we need to add the Catena-X Logos in our headers at Tractus-X, thats a requirement from style guidelines: 
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/bdb77963-2968-43e4-a3a7-b67ba70cd2ec)

Now if we are seeking for the application not do depend in an external image repository where it can be linked to the application it make really much sense to have it in our repositories...
If we have it in the repo why then not to use it in the documentation. Specially if we are part of the Catena-X Use Case Reference Implementations...

**Comment by matbmoser** [comment]
> @AngelikaWittek I am confused. I was here thinking we need to add the Catena-X Logos in our headers at Tractus-X, thats a requirement from style guidelines: ![image](https://private-user-images.githubusercontent.com/71728767/309233347-bdb77963-2968-43e4-a3a7-b67ba70cd2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTAyMDUsIm5iZiI6MTcwOTI4OTkwNSwicGF0aCI6Ii83MTcyODc2Ny8zMDkyMzMzNDctYmRiNzc5NjMtMjk2OC00M2U0LWEzYTctYjY3YmE3MGNkMmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwNDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZTgxMDA5ZmFmZTUxMTNjYTM5MDUxMzk1OTQ4MzAxYTgxNDlmMGZlNjdiZmMxOTRmMDVkYjk4NDhlOGM2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9bdftcUJt8NhhJxv6Ud0BTtNwFPMlhqaurMoJCTYybA)
> 
> Now if we are seeking for the application not do depend in an external image repository where it can be linked to the application it make really much sense to have it in our repositories... If we have it in the repo why then not to use it in the documentation. Specially if we are part of the Catena-X Use Case Reference Implementations...



> @AngelikaWittek I am confused. I was here thinking we need to add the Catena-X Logos in our headers at Tractus-X, thats a requirement from style guidelines: ![image](https://private-user-images.githubusercontent.com/71728767/309233347-bdb77963-2968-43e4-a3a7-b67ba70cd2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTAzMDQsIm5iZiI6MTcwOTI5MDAwNCwicGF0aCI6Ii83MTcyODc2Ny8zMDkyMzMzNDctYmRiNzc5NjMtMjk2OC00M2U0LWEzYTctYjY3YmE3MGNkMmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzUwNTNkYmEzMDYxZDVlNThmMTU1NTliNzg0ZTE0OTdlMWUwMzk1ZDRhZWM3M2NmMzM2Y2ViNDkyNDczZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSJYNW6vq3Nxe1H6yf51hxT5jLMK8mLp3ioXhNFFMDs)
> 
> Now if we are seeking for the application not do depend in an external image repository where it can be linked to the application it make really much sense to have it in our repositories... If we have it in the repo why then not to use it in the documentation. Specially if we are part of the Catena-X Use Case Reference Implementations...
> 
> Final reflection from me... If it is a requirement and part of Tractus-X already why is this even a issue? Maybe a license can be added with the picture for example, that would be and idea. Like we do with the KITs.
