### ISSUE TITLE
Local deployment Issue

### ISSUE THREAD

**Issue by tanweersalah** [eclipse-tractusx/digital-product-pass#242]
Hi, 

I am trying to run the Product pass application locally, 

I have deployed below services required for Catena X locally for testing Product Pass:

1. MIW
2. KeyCloak
3. Vault
4. Consumer EDC both dataplane and control plane
5. Provider EDC both dataplane and control plane
6. Registry 
7. BPN Finder
8. Discovery Finder

I am able to communicate between consumer and provider EDC, and request the Registry Catalog.
 
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/31222891/f91e2537-003f-4edf-9322-7b97b2c23dd6)

but when initiating transfer, status remains as STARTED. it does not change.
which result in product pass getting timed out.

I need some assistance here, 

Is there any backend service required ?

**Comment by matbmoser** [comment]
Hi! Thanks for the issue ;) That's actually a problem from the EDC 0.5.3  and EDC 0.6.0 unfortunately. Our Digital Product Pass application in v2.1.3 is just compatible with the version 0.5.0.

In the next Digital Product Pass version we are implementing an workaround to solve this by not waiting for the transfer to be COMPLETED: https://github.com/catenax-ng/tx-digital-product-pass/pull/244

The first transfer is done to retrieve the Digital Twin from the Registry through the EDC.

But for the asset transfer, yes you need to store you DPP Aspects somewhen in a "Submodel Server"/Backend Service which stores json files. We have an option for you already in our repo for that: https://github.com/eclipse-tractusx/digital-product-pass/tree/main/deployment/infrastructure/edc-provider/data-service

Please let me know if it helped you  👍🏻

**Comment by matbmoser** [comment]
I am closing this tickets since I dont see any further action.
