### ISSUE TITLE
Update EDC version to v0.7.0

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#265]
### Description
The EDCs must be updated to the version `v0.7.0`, in order to fulfill the release **24.05** requirements.
Adjust the dpp backend (if necessary) and update documentation.

#### Affected components
- Consumer EDC
- Provider EDC
- Backend

### Acceptance Criteria

- [ ] To be compliant with the standards
- [ ] Digital Product Passes are able to retrieve through the new EDC version

### Additional Information

EDC Repository: https://github.com/eclipse-tractusx/tractusx-edc
Open API swagger: https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc

**Comment by saudkhan116** [comment]
There is a new configuration introduced in edc version, which require DIM settings and bdrs server configurations.

**Comment by matbmoser** [comment]
Flagged because we are waiting for the credentials when the E2E Test starts

**Comment by matbmoser** [comment]
Here there is a migration guide: 
https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/migration/Version_0.5.x_0.7.x.md

**Comment by matbmoser** [comment]
This needs to be changed: 

https://github.com/catenax-ng/tx-digital-product-pass/blob/a4441186eca9007645d2c05ec1ff9a6cc44b22ad/dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/DataTransferService.java#L1150-L1166

**Comment by matbmoser** [comment]
Work done by @saudkhan116 :
Latest Status:
- Catalog retrieved
- EDC Configured

Flagged:
- Waiting app technical user (bdpm, irs, discovery services, semantichub)
      - To be configured in the app release process in the portal

**Comment by matbmoser** [comment]
Working in this branch: https://github.com/catenax-ng/tx-digital-product-pass/tree/feature/edc7-integration

**Comment by matbmoser** [comment]
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/dd1a16c9-69e3-4232-94f2-31757b0cdda2)
Bug related to policy configuration selection solved. For new edc the actions are under odrl:type

**Comment by matbmoser** [comment]
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/c3f36790-8a09-4394-ad11-b01b3f7aead8)
First step worked!

**Comment by matbmoser** [comment]
![Image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/c04684fb-23eb-49af-9099-13386583ebcc)

Working on INT with the new edc!
