### ISSUE TITLE
Resolve IRS issues with the EDC v0.7.0

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#266]
### Current Behavior
The DPP-IRS does not work due to IRS-EDC version incompatibility. At the moment, DPP uses EDC version `0.6.0` which IRS doesn't support. The current development from the IRS is going on to support the EDC `v0.7.0`. 

### Expected Behavior
After the EDC version is updated to `v0.7.0`, IRS should be expected to work.

### Steps To Reproduce

- Deploy EDC `v0.6.0`
- Deploy IRS-API `v4.5.0`
- API call to register IRS Job

See IRS version compatibility matrix: https://github.com/eclipse-tractusx/item-relationship-service/blob/main/COMPATIBILITY_MATRIX.md

**Comment by matbmoser** [comment]
This needs to be changed: 

https://github.com/catenax-ng/tx-digital-product-pass/blob/a4441186eca9007645d2c05ec1ff9a6cc44b22ad/dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/DataTransferService.java#L1150-L1166

**Comment by matbmoser** [comment]
Here there is a migration guide: 
https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/migration/Version_0.5.x_0.7.x.md

**Comment by saudkhan116** [comment]
The issues from the IRS integration are now resolved here: https://github.com/eclipse-tractusx/digital-product-pass/tree/feature/irs



![Image](https://github.com/eclipse-tractusx/digital-product-pass/assets/98085363/d81c592b-6263-4acb-90f9-045195618b18)
