### ISSUE TITLE
Prepare Step by Step Tutorial for the Second Tractus-X Community Days DPP Worksession

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#268]
### Description
The digital product pass application will be exposed in the Second Tractus-X Community Days during a worksession. 
Therefore some documentation needs to be prepared to help the participants to play and have fun using the digital product pass application.

There must be a guideline on how to deploy the app, what are the main features, how to generate a QR code. Tasks are documented in the acceptance criteria.

### Acceptance Criteria/Tasks

- [x] Step by step Tutorial documentation on how to deploy the digital product pass using kubernetes and helm charts
- [x] Tutorial on how to provide data:
    - [x] Tutorial on how to create passports (Digital Product Pass).
    - [x] Tutorial on how to create digital twins with digital product pass
    - [x] Tutorial on how to create the identification and qr codes
    - [ ] Use [MXD](https://github.com/eclipse-tractusx/tutorial-resources/tree/main/mxd) as initial infrastructure
    - [ ] Guide on deploying other central components

- [x] Challenge to be completed by finding information in passports.
- [x] Guide how to use the application
- [x] Additional Test data for the application
- [ ] CSV/Form to JSON Script (Translate csv digital product pass to json digital product pass) enable no code creation and providing passports.

### Additional Information
> [!CAUTION]
> DO NOT PROVIDE ANY SPECIFIC SECRETS OR INTERNAL INFORMATION FROM THE COMPANIES OR INFRASTRUCTURE INVOLVED IN THE EVENT ORGANIZATION!

Information shall be stored in `docs\tutorials\*`

More details still pending to be discussed with the organizers from the event.

> [!TIP]
> Make it generic for any further interest in understanding how to use the DPP application.

**Comment by saudkhan116** [comment]
Here is the documentation from the guides: https://github.com/eclipse-tractusx/digital-product-pass/tree/main/dpp-tutorial

**Comment by matbmoser** [comment]
Picture from the planning board: (Still a bit messy):

![Image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/f67d1c85-4c29-4176-b769-d375663ae334)
