### ISSUE TITLE
Clean up repository and refactor frontend code.

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#269]
### Description
Until the end of consortia and for the release v24.05 we need to focus on cleaning the repository and also refactoring the frotnend code that is not anymore used.

### Acceptance Criteria

- [x] Clean up unnecessary documentation
- [x] Refactor and optimize workflows
- [x] Refactor helm charts
- [x] Remove unused features from the backend

Tasks:

- [x] Remove `init.values.sh` file
- [x] Update Arc42 to reflect latest changes

**Comment by saudkhan116** [comment]
Refactoring the frontend code is now not included in scope.

**Comment by matbmoser** [comment]
I have refactored the frontend code because of the severe bugs we were having.

**Comment by matbmoser** [comment]
Now the bugs are solved in the verification branch for frontend:
- Font Reloading Added
- Token reloading/refresh when 401 added
- Incorrect URL format refactored
- Refactored backend service js to more optimized request format with axios.
