### ISSUE TITLE
Integrate the new Digital Product Pass Model 5.0 + Battery Pass Model 6.0

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#270]
### Description
Based on the new models display the Digital Product Pass v4.0 +  the Battery Pass v5.0.

### Acceptance Criteria
- [x] Remove all the retrocompatibility since models are being deprecated
- [x] Create test data for the models 
- [ ] Create a model compatibility matrix in the fronted documentation (create a frontend readme) @matbmoser

**Comment by matbmoser** [comment]
Lastest Status:

- Battery Passport Model 5.0.0 Integrated


Flagged:
- Waiting

**Comment by saudkhan116** [comment]
INT environment is now working and changed can be integrated.
Transmission pass 2.0.0 is also included

**Comment by saudkhan116** [comment]
Correction: the new versions are:

- BatteryPass v6.0
- DigitalproductPass v5.0
- TransmissionPass v3.0

**Comment by matbmoser** [comment]
Integrated and closed
