### ISSUE TITLE
[DPP] Contract negotiation failing because of CORS and check of "/" at end of provider url in dt

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#274]
### Current Behavior
Usage of CORS is necessary when using two different bsae URLs for backend and frontend.
![image-2024-03-14-15-47-15-031](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/6f8d8faa-5af2-45c4-ac7f-c061281d7052)
There is a problem with cors with the agree, and negotaition status methods: 
Because we send the headers with the forcing of credentials.
This happens when you have the backend and the frontend separated in two instances. 

### Solution
Remove this property from the frontend
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/fa237115-c75f-4d0a-a95d-0657f442e98d)

### Expected Behavior
No CORS errors

**Comment by saudkhan116** [comment]
The bug is now resolved, but still need to be tested.

**Comment by matbmoser** [comment]
This shoudl be solved but where is the change? 

https://github.com/eclipse-tractusx/digital-product-pass/blob/8a9745e4483be4c4dfb1bc56009f58f235bc051d/dpp-frontend/src/services/BackendService.js#L289C2-L293C1 

Is still in a PR waiting to be merged?

**Comment by matbmoser** [comment]
Will be solved in #335
