### ISSUE TITLE
Backend and Frontend Image Workflow for Docker are not Working

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#278]
### Current Behavior
Backend:
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/1c40772f-5b25-4194-83ad-26fcd3eff605)
https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/8707847347
Frontend:
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/7d229a08-8351-43fc-a77f-ee8a746bc73c)
https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/8707847351

### Expected Behavior
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/3fe18a15-9096-45e3-96ff-9f8fe77a7c3c)

### Problems:
All the workflow steps that were shared are not moved to the respective steps, after refactor for splitting the logic in between two different jobs

Missing checkout repository for frontend:

https://github.com/eclipse-tractusx/digital-product-pass/compare/v2.2.0..15e73dbc005481d78c315ca22e1e9f29cee8c9f6#diff-e2568d644336fa1d58208a8dc4dbb8ab90925066d7916f8eee597ac8ad297d4fL59-L62

Missing build java for backend:
https://github.com/eclipse-tractusx/digital-product-pass/compare/v2.2.0..15e73dbc005481d78c315ca22e1e9f29cee8c9f6#diff-bcb4660648686ea5e55a0ca08b6ec2f8e2713d20c9a722f55560526df29bc8b7L62-L63

**Comment by saudkhan116** [comment]
Fixed the issues in respective workflow files:

Last successfull runs:
Frontend:  https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/8709170583
Backend: https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/8709170587

Solved in: https://github.com/eclipse-tractusx/digital-product-pass/commit/646e4f5f6fb137e51ed258caaabd78266312f377
