### ISSUE TITLE
Open API Swagger Workflow is not working

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#279]
### Current Behavior
The workflow for releasing the open API here: https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass is not working...

Workflow run: https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/8709170581

The reason probably is because the "tagging" configuration is done incorrectly since the versions are not "published":
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/19bf0565-ecd6-4a0c-b2b0-2e678a6c9be9)

### Expected Behavior

Have a published API in swagger hub with the workflow not failing

**Comment by saudkhan116** [comment]
Implemented in PR #295 and included in release `v2.3.0`
