### ISSUE TITLE
[DPP] Interoperability checks performed

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#299]
## Interoperabilty Requirements:

- [x] Provide an Business Problem & Process Definition overview (Flowchart, BPMN) that makes the business interaction tangible
- [x] Do you have a documented End User Benefits Statement that states who the beneficiaries of the interoperability are and what they gain?
- [x] Please demonstrate App Provider Commitments from at least 2 parties that will implement the suggested interoperability scenario
- [x] Please provide a visualization of the Architecture Functional Cut between Apps and Network to demonstrate which capabilities reside in applications vs the network
- [x] Have you executed a Business Semantic Alignment across the various application providers resulting in a documented understanding of the data objects, structures and semantics 
- [x] Did you execute a Mapping against Catena-X Architecture Framework? Which standardization candidates are you intending to use in your scenario, which ones did you decide not to use?
- [x] Please provide a Technical Integration Design (interaction diagrams) that shows the components, interactions and technical protocols that you are intending to implement

Information found in: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/business%20statement/BusinessStatement.md

## Open Tasks to do in the document:

- [x] Update with the list of latest models to be integrated in Github (compare with updated confluence)
- [x] Check for changes or typos in diagrams and text compared with last QG 24.03

**Comment by saudkhan116** [comment]
Already requested for the review and approval from Interop team.
