### ISSUE TITLE
[DPP] Threat Modelling Analysis passed

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#301]
# Thread Modelling details:

- [x] Contact with @RoKrish14 to get latest diagrams that needed to be added in github
- [x] Add Thread Modelling information in the `/docs/security/assessment`

**Comment by saudkhan116** [comment]
Contacted to @RoKrish14  and @szymonkowalczykzf for the review and approval.

**Comment by szymonkowalczykzf** [comment]
Created PR. Documented the security assessment report. Diagrams will be added shortly.

**Comment by szymonkowalczykzf** [comment]
Threat Modeling is of course approved.

**Comment by matbmoser** [comment]
PR was missing license headers and footer note, 

We will merge the PR to another branch add the missing information and then merge it to main :)
Thank you @szymonkowalczykzf

**Comment by matbmoser** [comment]
Threat modelling added here: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/security/security_assessment.md
