### ISSUE TITLE
[DPP] Prepare Release v2.3.0

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#309]
## Description

The release version `v2.3.0` from digital product passport needs to be published

## Acceptence Criteria

- [x] Changelog updated
- [x] Helm chart version updated
- [x] Check for dependencies

**Comment by saudkhan116** [comment]
The release tag is availabe here: https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v2.3.0

**Comment by matbmoser** [comment]
Great Job!
