### ISSUE TITLE
DPP Backend Receiver Endpoint

### ISSUE THREAD

**Issue by tanweersalah** [eclipse-tractusx/digital-product-pass#326]
Can you please tell which service this is pointing to.  

```
edc:
    receiverEndpoint: 'https://dpp.int.demo.catena-x.net/endpoint'
```

I want to deploy this locally , please share the repo link,

**Comment by tanweersalah** [comment]
My bad, i got confused this with some external service, 

Now I am able to receive the EDR but still some issues with the DTR, 

While requesting the Catalog from registry for a particular assetId, I am getting the empty list, it seems like some bug with DTR.

while requesting directly to DTR I am getting the response, 

<img width="1165" alt="Screenshot 2024-06-01 at 12 31 54 PM" src="https://github.com/eclipse-tractusx/digital-product-pass/assets/31222891/56c1339f-121b-461e-9e1c-a5548a5d6e7b">

But when the same assetid is being lookup from the EDC Data Plane , I am getting empty result. 

<img width="1145" alt="Screenshot 2024-06-01 at 12 31 29 PM" src="https://github.com/eclipse-tractusx/digital-product-pass/assets/31222891/178666aa-f3b1-4207-bab6-4ec9f1b6631f">



Can you please let me know which DTR version is working correctly with the product pass,

**Comment by tanweersalah** [comment]
I figure out the issue, I created the shell in registry with providerbpn ,

Now after updating it to consumer bpn I am getting the results.

So doest it mean for every consumer we have to create a shell descriptor in DTR ?

**Comment by matbmoser** [comment]
Good than this ticket can be closed! We can also talk in Wednesday about this topic and more questions you have.
