### ISSUE TITLE
[DPP] [Release 24.08] E2E Integration Test passed

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#366]
## Description

The End-to-end tests of the DPP application needs to be passed to qualify the release requirements for the release 24.08.

Release version: v4.0.1

## Acceptance Criteria

- [X] EDC v0.7.3
- [X] App working on INT environment
- [X]  Test Case updated
- [X]  Test Execution Done

**Comment by matbmoser** [comment]
We are waiting for the release v4.0.1 to be done, and then we can update the test case in the JIRA

**Comment by saudkhan116** [comment]
We have now a release version published https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v4.0.1
The E2E Tests are executed

**Comment by matbmoser** [comment]
Approved by @ds-meberle
