### ISSUE TITLE
[DPP] [Release 24.08] User Journey approved

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#368]
## Description

The user journey needs to be approved to quality the release checks 24.08.

Here is the "bussiness idea" of the DPP App:
https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/interoperability/InteroperabilityGuide.md

## Acceptance Criteria

- [x] Get approval from product owner/ someone from the experts group

**Comment by stanfaldin** [comment]
According to my understanding and consultation with experts from the CX DPP Expert Group, I hereby confirm the consistency of the release with the DPP User Journey

**Comment by matbmoser** [comment]
Wonderful!!!
