### ISSUE TITLE
[DPP] [Release 24.08] Interoperability checks

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#370]
## Description

- [ ] Describe a business problem statement & Process Definition overview (Flowchart, BPMN) that makes the business interaction tangible
- [ ] Do you have a documented End User Benefits Statement that states who the beneficiaries of the interoperability are and what they gain?
- [ ] Please demonstrate App Provider Comitments from at least 2 parties that will implement the suggested interoperability scenario
- [ ] Please provide a visualization of the Architecture Functional Cut between Apps and Network to demonstrate which capabilities reside in applications vs the network
- [ ] Have you executed a Business Semantic Alignment across the various application providers resulting in a documented understanding of the data objects, structures and semantics 
- [ ] Did you execute a Mapping against Catena-X Architecture Framework? Which standardization candidates are you intending to use in your scenario, which ones did you decide not to use?
- [ ] Please provide a Technical Integration Design (interaction diagrams) that shows the components, interactions and technical protocols that you are intending to implement

Information found in: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/business%20statement/BusinessStatement.md

## Acceptance Criteria

- [ ] Update with the list of latest models to be integrated in Github (compare with updated confluence)
- [ ] Check for changes or typos in diagrams and text compared with last QG 24.08

**Comment by matbmoser** [comment]
Its documented here: https://github.com/eclipse-tractusx/digital-product-pass/blob/hotfix/policy-config/docs/interoperability/InteroperabilityGuide.md

Additionally I have wrote a compatibility matrix: https://github.com/eclipse-tractusx/digital-product-pass/blob/hotfix/policy-config/COMPATIBILITY_MATRIX.md
