### ISSUE TITLE
[DPP] [Release 24.08] Data Sovereignty checks

### ISSUE THREAD

**Issue by saudkhan116** [eclipse-tractusx/digital-product-pass#371]
# Data Sovereignty Checks:

- [ ] The provider of the connector MUST ensure the consumption of data via the DSP protocol adhering to the released version of [CX-0018 standard](https://catena-x.net/fileadmin/user_upload/Standard-Bibliothek/Update_September23/CX-0018-EclipseDataConnector_EDC_-v.2.0.1.pdf). For example, using the Eclipse Data Space Connector on [Tractus X](https://github.com/eclipse-tractusx/tractusx-edc). 
    - [ ] The application MUST ensure that the consumer of the data is uniquely identifiable through its associated BPN-L.
    - [ ] This BPN-L must be used by this application to identify the data.
- [ ] The application MUST use the BPN-L of consumer of the data when consuming data via the DSP connector (e.g. EDC or managed EDC).
- [ ] A user of an application MUST be enforced to act within the constraints of the framework agreement by appropriate means (legal, technical,...).
- [ ] To agree to one or multiple contract offers for a queried data asset, the selection of the appropriate offer MUST be done through the consuming application ensuring to follow company-defined rules and regulations for a user of that application.

We are using EDC: 0.7.0

Policy Configuration Guide: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/data-sovereignty/PolicyConfigGuide.md

**Comment by matbmoser** [comment]
This is not required in 24.08. But we are compliant, since we were also compliant in the R24.05
