### ISSUE TITLE
[DPP] [BUG] EDC Contract exchange metadata is shown partially

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#373]
### Current Behavior
For some reason, the frontend component is not displaying accordantly the metadata retrieved from the backend.
Most of the information that is required to be show like policy information and contract ids is still shown, however the rest of the information that incoming like, asset type and other things are not being displayed correctly.

![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/76e51881-7f81-445f-b9f3-56d2fce1de83)

### Expected Behavior
Display the EDC metadata incoming from the backend properly

### Steps To Reproduce
- Retrieve data with the DPP Backend and visualize it in the frontend
- Go to the `Exchange` tab
- See the missing data parts.

**Comment by saudkhan116** [comment]
The issue is resolved and included in the Release `v24.08` (DPP release version: `v4.0.0`)
