### ISSUE TITLE
Remove all Catena-X (NG) references

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/digital-product-pass#412]
This issue tracks the removal of all occurrences of `CatenaX-ng` in this repository as part of the broader goal to deprecate this organization.

- [x] Search for `Catena-X (NG)` in code, configuration, and documentation.
- [x] Remove or adapt references accordingly.
- [ ] Close this issue once zero references remain.

Use this query to track your progress (overall): [GitHub Search Query](https://github.com/search?q=repo%3A[RepoName]+catenax-ng&type=code)

[This](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng+repo%3Aeclipse-tractusx%2Fdigital-product-pass&type=code) query should display only results in related repository

Work summarized in https://github.com/eclipse-tractusx/sig-release/issues/838

**Comment by matbmoser** [comment]
Sure this can be done

**Comment by matbmoser** [comment]
I am working in this branch: `hotfix/catenax-ng-ref`

**Comment by matbmoser** [comment]
Ok I have fixed everything.

Findings:
- References in the documentation 
- The data-service reference was outdated and pointed to catena-x at home:
   - It was updated but never merged to main: https://github.com/eclipse-tractusx/digital-product-pass/blob/feature/simple-backend/deployment/infrastructure/data-provider/simple-data-provider 
   - I have merged this branch content into the `data-service` helm chart eliminating the use of Catena-X NG
