### ISSUE TITLE
[Trufflehog Update]: Reference agreed trufflehof version commit

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#424]
# Description

In this line of code:

https://github.com/eclipse-tractusx/digital-product-pass/blob/edc081c7e244fe5802ef51310e08e729b46b25eb/.github/workflows/trufflehog.yaml#L68

Should be changed to:

```yaml
uses: trufflesecurity/trufflehog@7e78ca385fb82c19568c7a4b341c97d57d9aa5e1
```

To reference the version of the workflow. Can it also be named as `trufflehog.yml` instead of `trufflehog.yaml` then we can be pretty standards in the naming convention.

**Comment by saudkhan116** [comment]
Resolved
