### ISSUE TITLE
[TRG 5.08] Create Helm Tests and run without errors

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#44]
# Introduction

For the TRGs we need to create helm tests to test our deployment.

## What needs to be done?

- [x] Create helm tests
- [ ] Execute them without errors

**Comment by saudkhan116** [comment]
The helm tests are prepared and requirement is fulfilled in PR https://github.com/eclipse-tractusx/digital-product-pass/pull/93

**Comment by matbmoser** [comment]
Resolved in [#v1.0.0-rc1](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v1.0.0-rc1)!
Helm test is running without errors:
https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/5835568223
