### ISSUE TITLE
[TRG 4.05 & TRG 4.06] Released image must be place `DockerHub` as mandatory container registry

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#50]
# Introduction

Move the image release to dockerhub

## What needs to be done:

- Change the url to dockerhub
- [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) Notice File for DockerHub has all necessary information
 TRG 4.06 Link to the source of your base image (Container registry and GitHub if available)
 TRG 4.06 Link to your product image on DockerHub
 TRG 4.06 Link to your repository on GitHub
 TRG 4.06 Direct link to the Dockerfile used to build your image
 TRG 4.06 Link to LICENCE file in your repo as Project License (make clear, that this is the PROJECT licence, not an image license

**Comment by saudkhan116** [comment]
**TRG 4.05**
Refactored contianer workflows and tested them in PR https://github.com/eclipse-tractusx/digital-product-pass/pull/68

The following images are available on Docker Hub:

- https://hub.docker.com/r/tractusx/digital-product-pass-frontend
- https://hub.docker.com/r/tractusx/digital-product-pass-backend

**Comment by matbmoser** [comment]
TRG 4.05 included in the following release #74 v1.0.0-alpha

**Comment by saudkhan116** [comment]
**TRG 4.06 - Notice for docker images**

Notice for docker images is included in release v1.0.0.
PR: https://github.com/eclipse-tractusx/digital-product-pass/pull/83
