### ISSUE TITLE
[TRG 5.11] Provide workflow to upgrade helm chart

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#51]
# Introduction
Based on the Helm test workflow, you must provide a GitHub action which takes the latest released helm chart, does an installation of it and then execute the upgrade to the current / new version.

## What needs to be done:
- [x] Create upgrade workflow

**Comment by saudkhan116** [comment]
**TRG 5.11**
Prepared a git workflow to achieve pre-release upgradeability. This change will be available in the next release v1.0.0
PR created: https://github.com/eclipse-tractusx/digital-product-pass/pull/90
