### ISSUE TITLE
[TRG 7.07] Legal notice for documentation

### ISSUE THREAD

**Issue by dsrparracho** [eclipse-tractusx/digital-product-pass#60]
## Introduction
In the TRG 7.07 there is the requirement that we should reference the Creative Commons Attribution 4.0 International license information in all Markdown (.md) files.

## What needs to be done?
Add a License heading in every markdown file with the following information:
 * SPDX-License-Identifier: CC-BY-4.0
 * Licence Path: https://creativecommons.org/licenses/by/4.0/legalcode
 * Copyright statements
 * Source URL: <URL to the repository>

**Comment by matbmoser** [comment]
Is still not clear what needs to be with the CC-BY license. We wait to clarification.

**Comment by matbmoser** [comment]
No clarification yet about this topic

**Comment by matbmoser** [comment]
There was a clarification from @SebastianBezold in this one: https://github.com/eclipse-tractusx/digital-product-pass/issues/108#issuecomment-1683553368

**Comment by saudkhan116** [comment]
The requirement to be implemented [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07/#documentation)

**Comment by matbmoser** [comment]
Included in main #127
