### ISSUE TITLE
[BUG] Values.yaml is not correct indented bug when helm install without env values

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#79]
## Introduction
There is a indent bug in the release v1.0.0-alpha

https://github.com/eclipse-tractusx/digital-product-pass/blob/dd30d63a0d6bf2efeba6186a87f6967296d5838a/charts/digital-product-pass/values.yaml#L156

### What needs to be done?
Correct the indentation.

**Comment by saudkhan116** [comment]
Fixed indentation issue in helm values.yaml.
Pull Request: https://github.com/eclipse-tractusx/digital-product-pass/pull/93
