### ISSUE TITLE
[TRG 4.02] Check compliance with add mandatory image for frontend, add image names to readme

### ISSUE THREAD

**Issue by dsrparracho** [eclipse-tractusx/digital-product-pass#82]
## Introduction
Due to legal constrains we need to annotate the released container images to make it clear that we do our best to provide good images for demo purposes, but we do not provide any legal guarantee. To make that process easy, we are aligning on agreed base images for specific languages and use an aligned section to describe the base image.

Since many of our Eclipse Tractus-X product use the same language, we are aligning on a dedicated container base image per language. The following table lists container base images, that are already agreed on.
Language / Runtime | Container base image | Notes
-- | -- | --
Java / Kotlin / JVM based | Eclipse Temurin | prefer JRE over JDK and alpine tags for your JRE version
JS frontends | nginx-unprivileged | prefer :stable-alpine tag
.NET runtime | .NET runtime | prefer :alpine tag
ASP.NET runtime | ASP.NET core runtime | prefer :alpine tag

## What needs to be done?
Add the base images used in the project to the README.md file.

**Comment by matbmoser** [comment]
This issue is duplicated from #42

**Comment by matbmoser** [comment]
https://github.com/eclipse-tractusx/digital-product-pass/pull/89
